### ISSUE TITLE
removing string matching from graphql tests

### ISSUE THREAD

**Issue by sohamda** [johanjanssen/JavaHiddenGems#155]
Hi Johan,

I have an idea to remove the string matching from graphql tests.
I tried checkout. create a branch and commit+push my code, but it gave me 403.
Is there something I doing wrong here?

Thanks
Soham

P.S.: this is in my Intellij GIT logs
14:49:05.352: [JavaHiddenGems] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false push --progress --porcelain origin refs/heads/dgs_client_builder:refs/heads/dgs_client_builder --set-upstream
remote: Permission to johanjanssen/JavaHiddenGems.git denied to sohamda.
fatal: unable to access 'https://github.com/johanjanssen/JavaHiddenGems.git/': The requested URL returned error: 403

**Comment by johanjanssen** [comment]
Hi Soham,

It looks like you're trying to push directly to my repo? 

Normally you need to create a fork in your repository, make the changes there and then create a PR so it's merged to my repo.

Kind regards,
Johan
